config/routes.rb
Rails.application.routes.draw do
  resources :localidades

  resources :tabelas, only: [:index]
  resources :clientes
  resources :tabela_precos_valores
  resources :itinerarios
  resources :cooperados
  
  mount Ckeditor::Engine => '/ckeditor'

  get '/localidades/:id/teste', to: "localidades#teste"
  
  root "welcome#index"
  get 'welcome/index'
  get "welcome/localizar", as: 'localizar'

  post "sign_up", to: "usuarios#create", as: "usuarios"
  get "sign_up", to: "usuarios#new"

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "sair"
  get "login", to: "sessions#new"

  get "edit_usuario", to: "usuarios#edit"
  patch "/usuarios/:id", to: "usuarios#update", as: "usuario"
  put "/usuarios/:id", to: "usuarios#update"

end

app/models/localidade.rb
class Localidade < ApplicationRecord
end

app/controllers/localidades_controller.rb
class LocalidadesController < ApplicationController
  before_action :set_localidade, only: %i[ show edit update destroy ]

  # GET /localidades or /localidades.json
  def index
    if params[:query].present?
      @pagy, @localidades = pagy(Localidade.where("nome LIKE ?", "%#{params[:query]}%").order(:nome))
    else
      @pagy, @localidades = pagy(Localidade.all.order(:nome))
    end
  end

  # GET /localidades/1 or /localidades/1.json
  def show
  end

  def teste
    @localidades = Localidade.find(params[:id])
  end

  # GET /localidades/new
  def new
    @localidade = Localidade.new
  end

  # GET /localidades/1/edit
  def edit
  end

  # POST /localidades or /localidades.json
  def create
    @localidade = Localidade.new(localidade_params)

    respond_to do |format|
      if @localidade.save
        format.html { redirect_to localidade_url(@localidade), notice: "Localidade was successfully created." }
        format.json { render :show, status: :created, location: @localidade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @localidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localidades/1 or /localidades/1.json
  def update
    respond_to do |format|
      if @localidade.update(localidade_params)
        format.html { redirect_to localidade_url(@localidade), notice: "Localidade was successfully updated." }
        format.json { render :show, status: :ok, location: @localidade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @localidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localidades/1 or /localidades/1.json
  def destroy
    @localidade.destroy

    respond_to do |format|
      format.html { redirect_to localidades_url, notice: "Localidade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_localidade
      @localidade = Localidade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def localidade_params
      params.require(:localidade).permit(:nome, :latitude, :longitude, :parada)
    end
end

app/helpers/localidades_helper.rb
module LocalidadesHelper
end

app/views/localidades/_botoes.html.erb
<% if action_name === "index" %>
    <a href='/localidades/new' class="w-[50px] mr-8">
      <svg fill="#4169e1" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 50 50" width="40px" height="40px"><path d="M25,2C12.317,2,2,12.317,2,25s10.317,23,23,23s23-10.317,23-23S37.683,2,25,2z M37,26H26v11h-2V26H13v-2h11V13h2v11h11V26z"/></svg>
    </a>
<% elsif action_name === "show" %>
   
    <div class="flex items-center">

    <%= button_to '<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
        width="32px" height="32px" viewBox="0 0 92 92" enable-background="new 0 0 92 92" xml:space="preserve" fill="#00b500">
    <path id="XMLID_1259_" d="M86.1,9.2L79,1.9C78.4,1.3,77.6,1,76.8,1h0c-0.8,0-1.6,0.3-2.1,0.9L32.8,44.4c-0.3,0.3-0.5,0.6-0.7,1
        l-4.7,11.9c-0.4,1.1-0.2,2.4,0.7,3.2c0.6,0.6,1.3,0.9,2.1,0.9c0.4,0,0.7-0.1,1.1-0.2l11.8-4.7c0.4-0.2,0.7-0.4,1-0.7l41.9-42.5
        C87.3,12.2,87.3,10.3,86.1,9.2z M40.4,51.2l-4.8,1.9l1.9-4.9L76.8,8.3l3,3L40.4,51.2z M71,47.6V88c0,2.2-2,4-4.2,4H10
        c-2.2,0-4-1.8-4-4V11.8C6,9.6,7.8,8,10,8h41.6c2.2,0,4,1.8,4,4s-1.8,4-4,4H14v68h49V47.6c0-2.2,1.8-4,4-4S71,45.4,71,47.6z"/>
    </svg>'.html_safe, edit_localidade_path(@localidade), method: :get, class: "w-[50px]" %>

    <%= button_to '<svg fill="#a60000" xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 64 64" width="40px" height="40px"><path d="M 28 7 C 25.243 7 23 9.243 23 12 L 23 15 L 13 15 C 11.896 15 11 15.896 11 17 C 11 18.104 11.896 19 13 19 L 15.109375 19 L 16.792969 49.332031 C 16.970969 52.510031 19.600203 55 22.783203 55 L 41.216797 55 C 44.398797 55 47.029031 52.510031 47.207031 49.332031 L 48.890625 19 L 51 19 C 52.104 19 53 18.104 53 17 C 53 15.896 52.104 15 51 15 L 41 15 L 41 12 C 41 9.243 38.757 7 36 7 L 28 7 z M 28 11 L 36 11 C 36.552 11 37 11.449 37 12 L 37 15 L 27 15 L 27 12 C 27 11.449 27.448 11 28 11 z M 19.113281 19 L 44.886719 19 L 43.212891 49.109375 C 43.153891 50.169375 42.277797 51 41.216797 51 L 22.783203 51 C 21.723203 51 20.846109 50.170328 20.787109 49.111328 L 19.113281 19 z M 32 23.25 C 31.033 23.25 30.25 24.034 30.25 25 L 30.25 45 C 30.25 45.966 31.033 46.75 32 46.75 C 32.967 46.75 33.75 45.966 33.75 45 L 33.75 25 C 33.75 24.034 32.967 23.25 32 23.25 z M 24.642578 23.251953 C 23.677578 23.285953 22.922078 24.094547 22.955078 25.060547 L 23.652344 45.146484 C 23.685344 46.091484 24.462391 46.835938 25.400391 46.835938 C 25.421391 46.835938 25.441891 46.835938 25.462891 46.835938 C 26.427891 46.801938 27.183391 45.991391 27.150391 45.025391 L 26.453125 24.939453 C 26.419125 23.974453 25.606578 23.228953 24.642578 23.251953 z M 39.355469 23.251953 C 38.388469 23.224953 37.580875 23.974453 37.546875 24.939453 L 36.849609 45.025391 C 36.815609 45.991391 37.571109 46.801938 38.537109 46.835938 C 38.558109 46.836938 38.578609 46.835938 38.599609 46.835938 C 39.537609 46.835938 40.314656 46.091484 40.347656 45.146484 L 41.044922 25.060547 C 41.078922 24.094547 40.321469 23.285953 39.355469 23.251953 z"/></svg>'.html_safe, localidade_path(@localidade), method: :delete, class: "w-[50px]" %>

    <%= button_to '<svg
        width="28pt"
        height="28pt"
        version="1.1"
        viewBox="0 0 28 28"
        id="svg469"
        xmlns="http://www.w3.org/2000/svg"
        fill="currentColor"
        xmlns:svg="http://www.w3.org/2000/svg">
        <defs
          id="defs385" />
        <g
          id="g467">
          <path
            d="m 17.776932,7.9223074 h -7.578943 v -4.32009 l -7.9831578,6.315789 7.9831578,6.3157896 v -4.31991 h 7.578943 c 2.45053,0 4.42106,1.995699 4.42106,4.421053 0,2.425353 -1.9957,4.421052 -4.42106,4.421052 H 6.1558842 V 24.74757 H 17.776932 c 4.64843,0 8.4379,-3.789473 8.4379,-8.437895 0,-4.623157 -3.78947,-8.3873676 -8.4379,-8.3873676 z"
            id="path387"
            style="stroke-width:0.0451128" />
        </g>
      </svg>'.html_safe, localidades_path, method: :get, class: 'w-[50px]' %>

    </div>

<% elsif action_name === "edit" %>
    
    <%= link_to '<svg
        width="28pt"
        height="28pt"
        version="1.1"
        viewBox="0 0 28 28"
        id="svg469"
        xmlns="http://www.w3.org/2000/svg"
        fill="currentColor"
        xmlns:svg="http://www.w3.org/2000/svg">
        <defs
          id="defs385" />
        <g
          id="g467">
          <path
            d="m 17.776932,7.9223074 h -7.578943 v -4.32009 l -7.9831578,6.315789 7.9831578,6.3157896 v -4.31991 h 7.578943 c 2.45053,0 4.42106,1.995699 4.42106,4.421053 0,2.425353 -1.9957,4.421052 -4.42106,4.421052 H 6.1558842 V 24.74757 H 17.776932 c 4.64843,0 8.4379,-3.789473 8.4379,-8.437895 0,-4.623157 -3.78947,-8.3873676 -8.4379,-8.3873676 z"
            id="path387"
            style="stroke-width:0.0451128" />
        </g>
      </svg>'.html_safe, localidade_path(@localidade), class: 'w-[50px]' %>

<% elsif action_name === "new" %>

    <%= link_to '<svg
        width="28pt"
        height="28pt"
        version="1.1"
        viewBox="0 0 28 28"
        id="svg469"
        xmlns="http://www.w3.org/2000/svg"
        fill="currentColor"
        xmlns:svg="http://www.w3.org/2000/svg">
        <defs
          id="defs385" />
        <g
          id="g467">
          <path
            d="m 17.776932,7.9223074 h -7.578943 v -4.32009 l -7.9831578,6.315789 7.9831578,6.3157896 v -4.31991 h 7.578943 c 2.45053,0 4.42106,1.995699 4.42106,4.421053 0,2.425353 -1.9957,4.421052 -4.42106,4.421052 H 6.1558842 V 24.74757 H 17.776932 c 4.64843,0 8.4379,-3.789473 8.4379,-8.437895 0,-4.623157 -3.78947,-8.3873676 -8.4379,-8.3873676 z"
            id="path387"
            style="stroke-width:0.0451128" />
        </g>
      </svg>'.html_safe, localidades_path, class: 'w-[50px]' %>      

<% end %>

app/views/localidades/_form.html.erb
<%= form_with(model: localidade, local: true, data: {
                                            controller: :maps,
                                            action: "google-maps-callback@window->maps#initializeMap"
                                          }, class: "contents") do |form| %>
  <% if localidade.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(localidade.errors.count, "error") %> prohibited this localidade from being saved:</h2>

      <ul>
        <% localidade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :nome %>
    <%= form.text_field :nome, data: { target: "maps.field", action: "keydown->maps#preventSubmit" }, class: "block shadow rounded-md border border-solid border-gray-300 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="flex justify-between">

  <div class="my-5 w-full mr-2">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, data: { target: "maps.latitude" }, class: "block shadow rounded-md bg-gray-300 border border-solid border-gray-300 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5 w-full ml-2">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, data: { target: "maps.longitude" }, class: "block shadow rounded-md bg-gray-300 border border-solid border-gray-300 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= content_tag :div, nil, data: { target: "maps.map" }, class: 'map' %>


  </div>

  <div class="my-5">
    <%= form.label :parada %>
    <%= form.check_box :parada, class: "block mt-2 h-5 w-5" %>
  </div>

  <%= content_tag :div, nil, data: { target: "maps.map" }, class: 'map' %>

  <div class="inline my-5">
    <%= form.submit "Salvar", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/localidades/_localidade.html.erb
<div id="<%= dom_id localidade %>" class="bg-white shadow px-5 py-2 border border-1 border-gray-500 rounded m-5 w-full">
<% if action_name === "index" %>
  <a href='localidades/<%= localidade.id %>'>
    <li class="flex items-center bg-white p-2 hover:shadow-lg rounded cursor-pointer transition">
        <div class="flex flex-col ml-2 w-full">
          <div class="flex justify-between font-medium text-black">
            <span class="truncate"><%= localidade.nome %></span>
            <% if localidade.parada? %><span class="flex bg-green-500 px-5 rounded-full text-xs text-white items-center">Parada</span><% end %>
          </div>
          <p>Lat.: <%= localidade.latitude %></p>
          <p>Lgt.: <%= localidade.longitude %></p>
        </div>
    </li>
  </a>
<% else %>
    <li class="flex items-center flex-col bg-white p-2 hover:shadow-lg rounded cursor-pointer transition">
        <div class="flex flex-col ml-2 w-full my-5">
          <div class="flex justify-between font-medium text-black truncate">
            <span class="truncate"><%= localidade.nome %></span>
            <% if localidade.parada? %><span class="flex bg-green-500 px-5 rounded-full text-xs text-white items-center">Parada</span><% end %>
          </div>
          <p>Latitude: <%= localidade.latitude %></p>
          <p>Longitude: <%= localidade.longitude %></p>
          <div class="p-5">
          <%= form_with(url: welcome_url, method: :get, data: {
                                                  controller: :maps,
                                                  action: "google-maps-callback@window->maps#initializeMap"
                                                }, class: "contents") do |form| %>
          <div class="hidden">
            <%= form.text_field :latitude, value: localidade.latitude, data: { target: "maps.latitude" } %>
          </div>
          <div class="hidden">
            <%= form.text_field :longitude, value: localidade.longitude, data: { target: "maps.longitude" } %>
          </div>
          <%= content_tag :div, nil, data: { target: "maps.map" }, class: 'map' %>
          <% end %>
          </div>
        </div>
    </li>
<% end %>
</div>

app/views/localidades/_localidades.html.erb
<%= turbo_frame_tag "localidades" do %>
  <%= render localidades %>
<% end %>

app/views/localidades/edit.html.erb
<div class="flex flex-col w-full bg-white text-gray-600 shadow z-10 top-0">
     
  <div class="flex justify-between h-16 content-center items-center">
    <p class="py-2 mx-4 text-4xl">Editando Localidade</p>
    <%= render 'botoes' %>
  </div>

</div>

<div class="flex flex-col w-3/4 bg-white shadow p-5 my-10">
	
  <%= render "form", localidade: @localidade %>

</div>

app/views/localidades/index.html.erb
<div class="flex flex-col w-full bg-white text-gray-600 shadow">
   
  <div class="flex justify-between h-16 content-center items-center">
    <p class="py-2 mx-4 text-4xl">Listando Localidades</p>
    <%= render 'botoes' %>
  </div>

</div>

<div class="my-4 mx-auto px-4 md:px-12"><ul>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-0 sm:gap-4">
        <%= render @localidades %>
    </div></ul>
</div>

<div class="max-w-content flex flex-row flex-no-wrap my-5 mx-10 text-xs text-gray-700">
   <%== pagy_bulma_nav(@pagy) %>
</div>

app/views/localidades/new.html.erb
<div class="flex flex-col w-full bg-white text-gray-600 shadow z-10 top-0">
     
  <div class="flex justify-between h-16 content-center items-center">
    <p class="py-2 mx-4 text-4xl">Nova Localidade</p>
    <%= render 'botoes' %>
  </div>

</div>

<div class="flex flex-col w-3/4 bg-white shadow p-5 my-10">
	
  <%= render "form", localidade: @localidade %>

</div>

app/views/localidades/show.html.erb
<div class="flex flex-col w-full bg-white text-gray-600 shadow">
   
  <div class="flex justify-between h-16 content-center items-center">
    <p class="py-2 mx-4 text-4xl">Exibindo Localidade</p>
    <%= render 'botoes' %>
  </div>

</div>

<div class="w-3/4 my-4 mx-auto px-4 md:px-12">
    <%= render @localidade %>
</div>

app/views/localidades/teste.html.erb
<div class="flex flex-col w-full bg-white text-gray-600 shadow">
   
  <div class="flex justify-between h-16 content-center items-center">
    <p class="py-2 mx-4 text-4xl">Exibindo Localidade</p>
    <%= render 'botoes' %>
  </div>

</div>

<div class="w-3/4 my-4 mx-auto px-4 md:px-12">
    <div id="" class="bg-white shadow px-5 py-2 border border-1 border-gray-500 rounded m-5 w-full">
        <li class="flex items-center bg-white p-2 hover:shadow-lg rounded cursor-pointer transition">
            <div class="flex flex-col ml-2 w-full" data-controller="maps" data-action="google-maps-callback@window->maps#initializeMap">
                <p><%= @localidades.id %></p>
                <p><%= @localidades.nome %></p>
		<p><%= @localidades.latitude %></p>
		<p><%= @localidades.longitude %></p>
		<%= content_tag :div, nil, data: { target: "maps.map" }, class: 'map' %>
            </div>
        </li>
    </div>
</div>