config/routes.rb
Rails.application.routes.draw do
  resources :localidades

  resources :tabelas, only: [:index]
  resources :clientes
  resources :tabela_precos_valores
  resources :itinerarios
  resources :cooperados
  
  mount Ckeditor::Engine => '/ckeditor'

  get '/localidades/:id/teste', to: "localidades#teste"
  
  root "welcome#index"
  get 'welcome/index'
  get "welcome/localizar", as: 'localizar'

  post "sign_up", to: "usuarios#create", as: "usuarios"
  get "sign_up", to: "usuarios#new"

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "sair"
  get "login", to: "sessions#new"

  get "edit_usuario", to: "usuarios#edit"
  patch "/usuarios/:id", to: "usuarios#update", as: "usuario"
  put "/usuarios/:id", to: "usuarios#update"

end

app/models/active_session.rb
class ActiveSession < ApplicationRecord
    belongs_to :usuario
end  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	validates_presence_of :nome, :cpf_cnpj
	validates_uniqueness_of :sigla

	has_one_attached :imagem
end

app/models/cooperado.rb
class Cooperado < ApplicationRecord
	validates_presence_of :nome, :matricula
	validates_uniqueness_of :matricula

	has_one_attached :imagem
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :usuario
end

app/models/itinerario.rb
class Itinerario < ApplicationRecord
end

app/models/localidade.rb
class Localidade < ApplicationRecord
end

app/models/tabela_precos_valor.rb
class TabelaPrecosValor < ApplicationRecord
  belongs_to :tabela_preco
  belongs_to :itinerario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    has_secure_password

    has_many :active_sessions, dependent: :destroy

    def self.authenticate_by(attributes)
        passwords, identifiers = attributes.to_h.partition do |name, value|
          !has_attribute?(name) && has_attribute?("#{name}_digest")
        end.map(&:to_h)
    
        raise ArgumentError, "One or more password arguments are required" if passwords.empty?
        raise ArgumentError, "One or more finder arguments are required" if identifiers.empty?
        if (record = find_by(identifiers))
          record if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
        else
          new(passwords)
          nil
        end
      end    

      has_one_attached :imagem
      
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

    skip_before_action :authenticate_usuario!

    def encode_token(payload)
        JWT.encode(payload,'secret')
    end

    def decode_token
        auth_token = request.headers['Authorization']
        if auth_token
            token=auth_token.split(' ').last
            begin
                JWT.decode(token,'secret', true, algorithm: 'HS256')
            rescue JWT::DecodeError
                nil
            end
        end
    end

    def usuario_autorizado
        decoded_token = decode_token()
        if decoded_token
            usuario_id = decoded_token[0]['usuario_id']
            @usuario = Usuario.find_by(id: usuario_id)
        end
    end

    def autorizar
        render json: { message: 'Você precisa estar logado'}, status: :unauthorized unless usuario_autorizado
    end    
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    if params[:query].present?
      @pagy, @clientes = pagy(Cliente.where("nome LIKE ?", "%#{params[:query]}%").order(:nome))
    else
      @pagy, @clientes = pagy(Cliente.all.order(:nome))
    end
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente criado com sucesso." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente excluido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf_cnpj, :sigla, :logradouro, :numero, :complemento, :bairro, :cidade, :estado, :cep, :telefone, :email, :imagem)
    end
end

app/controllers/tabelas_controller.rb
class TabelasController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def localizar
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/cooperados_helper.rb
module CooperadosHelper
end

app/helpers/itinerarios_helper.rb
module ItinerariosHelper
end

app/helpers/localidades_helper.rb
module LocalidadesHelper
end

app/helpers/tabelas_helper.rb
module TabelasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MasterTaxi - Gerenciador de Corridas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Figaro.env.google_api}&libraries=places&callback=dispatchMapsEvent", 
                                                  async: true, 
                                                  defer: true, 
                                                  "data-turbolinks-eval": false %>
    <%= javascript_importmap_tags %>

    <meta name="theme-color" content="#ffffff">

  </head>

  <body>
    <div class="flex bg-gray-300">
      <div class="flex flex-col w-64 h-screen px-4 py-8 overflow-y-auto border-r bg-indigo-900 sticky top-0">
          <%= render '/shared/sidebar' %>
      </div>
      <div class="w-full h-full overflow-y-auto">
        <div class="flex flex-col items-center justify-center">
          <%= yield %>
        </div>
      </div>  
  </body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MasterTaxi - Gerenciador de Corridas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-white dark:bg-gray-800">
<div class="container px-6 py-4 mx-auto">
    <div class="lg:flex">
        <div class="w-full -mx-6 lg:w-2/5">
            <div class="px-6">
                <div>
                    <a href="#" class="text-xl font-bold text-gray-800 dark:text-white hover:text-gray-700 dark:hover:text-gray-300">Brand</a>
                </div>
                
                <p class="max-w-md mt-2 text-gray-500 dark:text-gray-400">Join 31,000+ other and never miss out on new tips, tutorials, and more.</p>
                
                <div class="flex mt-4 -mx-2">
                    <a href="#" class="mx-2 text-gray-700 dark:text-gray-200 hover:text-gray-600 dark:hover:text-gray-400" aria-label="Linkden">
                        <svg class="w-4 h-4 fill-current" viewBox="0 0 512 512">
                            <path d="M444.17,32H70.28C49.85,32,32,46.7,32,66.89V441.61C32,461.91,49.85,480,70.28,480H444.06C464.6,480,480,461.79,480,441.61V66.89C480.12,46.7,464.6,32,444.17,32ZM170.87,405.43H106.69V205.88h64.18ZM141,175.54h-.46c-20.54,0-33.84-15.29-33.84-34.43,0-19.49,13.65-34.42,34.65-34.42s33.85,14.82,34.31,34.42C175.65,160.25,162.35,175.54,141,175.54ZM405.43,405.43H341.25V296.32c0-26.14-9.34-44-32.56-44-17.74,0-28.24,12-32.91,23.69-1.75,4.2-2.22,9.92-2.22,15.76V405.43H209.38V205.88h64.18v27.77c9.34-13.3,23.93-32.44,57.88-32.44,42.13,0,74,27.77,74,87.64Z"/>
                        </svg>
                    </a>

                    <a href="#" class="mx-2 text-gray-700 dark:text-gray-200 hover:text-gray-600 dark:hover:text-gray-400" aria-label="Facebook">
                        <svg class="w-4 h-4 fill-current" viewBox="0 0 512 512">
                            <path d="M455.27,32H56.73A24.74,24.74,0,0,0,32,56.73V455.27A24.74,24.74,0,0,0,56.73,480H256V304H202.45V240H256V189c0-57.86,40.13-89.36,91.82-89.36,24.73,0,51.33,1.86,57.51,2.68v60.43H364.15c-28.12,0-33.48,13.3-33.48,32.9V240h67l-8.75,64H330.67V480h124.6A24.74,24.74,0,0,0,480,455.27V56.73A24.74,24.74,0,0,0,455.27,32Z"/>
                        </svg>
                    </a>

                    <a href="#" class="mx-2 text-gray-700 dark:text-gray-200 hover:text-gray-600 dark:hover:text-gray-400" aria-label="Twitter">
                        <svg class="w-4 h-4 fill-current" viewBox="0 0 512 512">
                            <path d="M496,109.5a201.8,201.8,0,0,1-56.55,15.3,97.51,97.51,0,0,0,43.33-53.6,197.74,197.74,0,0,1-62.56,23.5A99.14,99.14,0,0,0,348.31,64c-54.42,0-98.46,43.4-98.46,96.9a93.21,93.21,0,0,0,2.54,22.1,280.7,280.7,0,0,1-203-101.3A95.69,95.69,0,0,0,36,130.4C36,164,53.53,193.7,80,211.1A97.5,97.5,0,0,1,35.22,199v1.2c0,47,34,86.1,79,95a100.76,100.76,0,0,1-25.94,3.4,94.38,94.38,0,0,1-18.51-1.8c12.51,38.5,48.92,66.5,92.05,67.3A199.59,199.59,0,0,1,39.5,405.6,203,203,0,0,1,16,404.2,278.68,278.68,0,0,0,166.74,448c181.36,0,280.44-147.7,280.44-275.8,0-4.2-.11-8.4-.31-12.5A198.48,198.48,0,0,0,496,109.5Z"/>
                        </svg>
                    </a>
                </div>
            </div>
        </div>

        <div class="mt-6 lg:mt-0 lg:flex-1">
            <div class="grid grid-cols-2 gap-6 sm:grid-cols-3 md:grid-cols-4">
                <div>
                    <h3 class="text-gray-700 uppercase dark:text-white">About</h3>
                    <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Company</a>
                    <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">community</a>
                    <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Careers</a>
                </div>

                <div>
                    <h3 class="text-gray-700 uppercase dark:text-white">Blog</h3>
                    <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Tec</a>
                    <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Music</a>
                    <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Videos</a>
                </div>

                <div>
                    <h3 class="text-gray-700 uppercase dark:text-white">Products</h3>
                    <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Mega cloud</a>
                    <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Aperion UI</a>
                    <a href="#" class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">Meraki UI</a>
                </div>

                <div>
                    <h3 class="text-gray-700 uppercase dark:text-white">Contact</h3>
                    <span class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">+1 526 654 8965</span>
                    <span class="block mt-2 text-sm text-gray-600 dark:text-gray-400 hover:underline">example@email.com</span>
                </div>
            </div>
        </div>
    </div>

    <hr class="h-px my-6 bg-gray-300 border-none dark:bg-gray-700">

    <div>
        <p class="text-center text-gray-800 dark:text-white">© Brand 2020 - All rights reserved</p>
    </div>
</div>
</footer>    

app/views/shared/_sidebar.html.erb
<%
    root = Rails.root.to_s #make sure string    
    puts "#{root}/public/menu.json"
    file = File.read("#{root}/public/menu.json")
    json_object = JSON.parse(file)
%>



    <div class="pt-5 pb-2 px-6">

        <div class="grow flex justify-center w-full">

            <h2 class="text-3xl font-semibold text-gray-200"><%= Figaro.env.app_name %></h2>

        </div>

    </div>

    <hr class="my-6 border-gray-600" />
  
    <div class="flex flex-col justify-between flex-1 text-sm">
        <nav>
            <% json_object.each do |menu| %>
                <div class="flex items-center text-gray-300 font-medium my-4">         
                <span class='mx-2'><%= menu["icon"].html_safe %></span>
                <%= link_to menu["label"], menu["url"], class: 'ml-2' %>
                </div>
            <% end %>

            <hr class="my-6 border-gray-600" />

            <div>
            <%= button_to sair_path, method: :delete, class: "flex items-center text-gray-300 font-medium my-4" do  %>
                <span class="mx-2">
                    <svg
                    version="1.1"
                    id="Layer_1"
                    x="0px"
                    y="0px"
                    width=22
                    height=22
                    viewBox="0 0 24.000001 24.000001"
                    xml:space="preserve"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                    xmlns:svg="http://www.w3.org/2000/svg"><defs
                    id="defs63" />
                    <g
                    id="g22"
                    transform="matrix(0.04296865,0,0,0.04296865,0.76113647,1.1494879)">
                        <g
                    id="g20">
                            <path
                    d="m 450.88,53.36 c -4.364,-4.363 -10.282,-6.814 -16.455,-6.814 -0.002,0 -0.005,0 -0.006,0 l -23.267,0.008 v 23.273 23.273 325.81 23.273 23.273 h 23.273 c 12.853,0 23.273,-10.42 23.273,-23.273 V 69.819 C 457.697,63.645 455.246,57.725 450.88,53.36 Z"
                    id="path18" />
                        </g>
                    </g>
                    <g
                    id="g28"
                    transform="matrix(0.9166668,0,0,0.9166668,1.2742917,1.1567054)">
                        <g
                    id="g26">
                            <path
                    d="M 16.14134,0.24726635 C 15.894263,0.03998562 15.568201,-0.04743604 15.250577,0.00881382 L 2.8869513,2.1919178 c -0.521295,0.092015 -0.90131,0.5449674 -0.90131,1.0742786 V 20.719403 c 0,0.529358 0.380062,0.982404 0.901357,1.074326 L 15.250624,23.97552 c 0.06314,0.01111 0.126468,0.01659 0.189515,0.01659 0.254484,0 0.503295,-0.08911 0.701248,-0.255187 0.247078,-0.207281 0.389671,-0.513186 0.389671,-0.835685 V 22.675117 21.810322 20.719403 19.628484 4.3567405 3.2658214 2.1749022 1.0830456 c 0,-0.3224524 -0.142593,-0.62840476 -0.389718,-0.83577925 z M 11.848116,13.491015 c -0.202827,0.202968 -0.484358,0.319265 -0.77156,0.319265 -0.287249,0 -0.567983,-0.116344 -0.771654,-0.319359 -0.202922,-0.203484 -0.3192647,-0.484217 -0.3192647,-0.77156 0,-0.28725 0.1163427,-0.568077 0.3192647,-0.771561 0.203624,-0.202968 0.484358,-0.319359 0.771654,-0.319359 0.287202,0 0.568733,0.116344 0.77156,0.319359 0.202922,0.203578 0.319359,0.484311 0.319359,0.771561 -4.7e-5,0.28739 -0.116484,0.568123 -0.319359,0.771654 z"
                    id="path24"
                    style="stroke-width:0.0468749" />
                        </g>
                    </g>
                    <g
                    id="g30">
                    </g>
                    <g
                    id="g32">
                    </g>
                    <g
                    id="g34">
                    </g>
                    <g
                    id="g36">
                    </g>
                    <g
                    id="g38">
                    </g>
                    <g
                    id="g40">
                    </g>
                    <g
                    id="g42">
                    </g>
                    <g
                    id="g44">
                    </g>
                    <g
                    id="g46">
                    </g>
                    <g
                    id="g48">
                    </g>
                    <g
                    id="g50">
                    </g>
                    <g
                    id="g52">
                    </g>
                    <g
                    id="g54">
                    </g>
                    <g
                    id="g56">
                    </g>
                    <g
                    id="g58">
                    </g>
                    </svg>              
                </span>
                <span class="ml-2">Sair do Sistema</span>
            <% end %>
            </div>

        </nav>

        <% if usuario_signed_in? %>
            <div class="pt-4 pb-2 px-6">

                <div class="flex flex-col items-center justify-center">
                    <div class="shrink-0">
                        <% if current_usuario.imagem.attached? %>
                            <%= image_tag(current_usuario.imagem, class: 'rounded-full w-[50px] h-[50px]  bg-gray-900') %>
                        <% end %>                        
                    </div>
                    <div class="grow flex justify-center w-full my-2">
                        <p class="text-sm font-semibold text-gray-200"><%= link_to current_usuario.nome, edit_usuario_path %></p>
                    </div>
                </div>
                
            </div>
        <% end %>
    </div>