config/routes.rb
Rails.application.routes.draw do
  resources :localidades

  resources :tabelas, only: [:index]
  resources :clientes
  resources :tabela_precos_valores
  resources :itinerarios
  resources :cooperados
  
  mount Ckeditor::Engine => '/ckeditor'

  get '/localidades/:id/teste', to: "localidades#teste"
  
  root "welcome#index"
  get 'welcome/index'
  get "welcome/localizar", as: 'localizar'

  post "sign_up", to: "usuarios#create", as: "usuarios"
  get "sign_up", to: "usuarios#new"

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "sair"
  get "login", to: "sessions#new"

  get "edit_usuario", to: "usuarios#edit"
  patch "/usuarios/:id", to: "usuarios#update", as: "usuario"
  put "/usuarios/:id", to: "usuarios#update"

end

app/models/active_session.rb
class ActiveSession < ApplicationRecord
    belongs_to :usuario
end  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	validates_presence_of :nome, :cpf_cnpj
	validates_uniqueness_of :sigla

	has_one_attached :imagem
end

app/models/cooperado.rb
class Cooperado < ApplicationRecord
	validates_presence_of :nome, :matricula
	validates_uniqueness_of :matricula

	has_one_attached :imagem
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :usuario
end

app/models/itinerario.rb
class Itinerario < ApplicationRecord
end

app/models/localidade.rb
class Localidade < ApplicationRecord
end

app/models/tabela_precos_valor.rb
class TabelaPrecosValor < ApplicationRecord
  belongs_to :tabela_preco
  belongs_to :itinerario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    has_secure_password

    has_many :active_sessions, dependent: :destroy

    def self.authenticate_by(attributes)
        passwords, identifiers = attributes.to_h.partition do |name, value|
          !has_attribute?(name) && has_attribute?("#{name}_digest")
        end.map(&:to_h)
    
        raise ArgumentError, "One or more password arguments are required" if passwords.empty?
        raise ArgumentError, "One or more finder arguments are required" if identifiers.empty?
        if (record = find_by(identifiers))
          record if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
        else
          new(passwords)
          nil
        end
      end    

      has_one_attached :imagem
      
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

    skip_before_action :authenticate_usuario!

    def encode_token(payload)
        JWT.encode(payload,'secret')
    end

    def decode_token
        auth_token = request.headers['Authorization']
        if auth_token
            token=auth_token.split(' ').last
            begin
                JWT.decode(token,'secret', true, algorithm: 'HS256')
            rescue JWT::DecodeError
                nil
            end
        end
    end

    def usuario_autorizado
        decoded_token = decode_token()
        if decoded_token
            usuario_id = decoded_token[0]['usuario_id']
            @usuario = Usuario.find_by(id: usuario_id)
        end
    end

    def autorizar
        render json: { message: 'Você precisa estar logado'}, status: :unauthorized unless usuario_autorizado
    end    
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    if params[:query].present?
      @pagy, @clientes = pagy(Cliente.where("nome LIKE ?", "%#{params[:query]}%").order(:nome))
    else
      @pagy, @clientes = pagy(Cliente.all.order(:nome))
    end
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente criado com sucesso." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente excluido com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf_cnpj, :sigla, :logradouro, :numero, :complemento, :bairro, :cidade, :estado, :cep, :telefone, :email, :imagem)
    end
end

app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :redirect_if_authenticated, only: [:create, :new]
    before_action :authenticate_usuario!, only: [:destroy]

    layout 'session'

    def create
      @usuario = Usuario.find_by(username: params[:usuario][:username].downcase)
      if @usuario
        if @usuario.authenticate(params[:usuario][:password])
          after_login_path = session[:usuario_return_to] || root_path
          login @usuario
          remember(@usuario) if params[:usuario][:remember_me] == "1"
          redirect_to after_login_path, notice: "Signed in."
        else
          flash.now[:alert] = "Incorrect username or password."
          render :new, status: :unprocessable_entity
        end
      else
        flash.now[:alert] = "Incorrect username or password."
        render :new, status: :unprocessable_entity
      end
    end
  
    def destroy
      forget_active_session
      logout
      redirect_to root_path, notice: "Signed out."
    end
  
    def new
    end
  
  end

app/controllers/tabelas_controller.rb
class TabelasController < ApplicationController
  def index
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApiController

    layout 'session', only: [:new]

        def create
            @usuario = Usuario.new(usuario_params)

            if @usuario.save
                redirect_to root_path, notice: "Please check your email for confirmation instructions."
            else
                render :new, status: :unprocessable_entity
            end
        end

        def new
            @usuario = Usuario.new
        end

        def edit
            @usuario = Usuario.find(current_usuario.id)
        end

        # PATCH/PUT /grupos/1 or /grupos/1.json
        def update
            respond_to do |format|
                if current_usuario.update(usuario_params)
                    format.html { redirect_to root_url, notice: "Grupo was successfully updated." }
                else
                    format.html { render :edit, status: :unprocessable_entity }
                end
            end
        end        

        private

        def usuario_params
            params.require(:usuario).permit(:username, :password, :password_confirmation, :nome, :bio, :grupo, :imagem)
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def localizar
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/cooperados_helper.rb
module CooperadosHelper
end

app/helpers/itinerarios_helper.rb
module ItinerariosHelper
end

app/helpers/localidades_helper.rb
module LocalidadesHelper
end

app/helpers/tabelas_helper.rb
module TabelasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/usuarios/_form.html.erb
<!-- app/views/users/new.html.erb -->
<%= form_with(model: usuario, class: "contents") do |form| %>
  
  <div class="my-5">
    <%= form.label :nome, class: "text-gray-800 text-sm" %>
    <%= form.text_field :nome, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bio, class: "text-gray-800 text-sm" %>
    <%= form.cktext_area :bio, as: :ckeditor, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full', input_html: { ckeditor: { toolbar: 'Full' } } %>
  </div>

  <div class="my-5">
    <%= form.label "Nome de Usuário", class: "text-gray-800 text-sm" %>
    <%= form.text_field :username, required: true, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
  </div>

  <div class="my-5">
    <%= form.label "Senha",  class: "text-gray-800 text-sm" %>
    <%= form.password_field :password, required: true, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
  </div>

  <div class="my=5">
    <%= form.label "Repita a sua senha", class: "text-white text-sm" %>
    <%= form.password_field :password_confirmation, required: true, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
  </div>

  <div class="my=5">
    <%= form.label :imagem, class: "text-gray-800 text-sm" %>
    <%= form.file_field :imagem, multiple: false, class: "my-5" %> 
  </div>   
    
  <div class="my=5">
    <%= form.label :imagem, class: "text-gray-800 text-sm" %>
    <% if usuario.imagem.attached? %>
        <%= image_tag(usuario.imagem, class: 'w-64 h-auto block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2') %>
    <% end %>        
  </div>  

  <div class="inline my-5">
    <%= form.submit "Criar Usuário", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer mt-2" %>
  </div>

<% end %>

app/views/usuarios/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Meus Dados</h1>

  <%= render "form", usuario: @usuario %>

</div>

app/views/usuarios/login.html.erb
<div class="mx-auto md:w-2/3 w-full">
  
  <h1 class="font-bold text-4xl">Login</h1>

  <%= render "form", usuario: @usuario %>

</div>

app/views/usuarios/new.html.erb
<div class="relative bg-gray-900">

<div class="hidden bg-cover lg:block relative md:fixed w-full md:w-7/12 lg:w-2/3 min-h-screen inset-0" style="background-image: url(<%= Figaro.env.picture_sessions %>)">

        <div class="flex flex-col justify-center mx-16 min-h-screen">
            <h1 class="text-white text-8xl">Master<span class="text-[#e0ae00]">Táxi</span></h1>
            <p class="text-white text-4xl">Gerenciador de Corridas</p>
        </div>

    </div>


    <div class="flex flex-col justify-center w-full md:w-5/12 lg:w-2/6 ml-auto px-12 min-h-screen py-4">

        <div class="text-center">
        
            <h2 class="text-4xl font-bold text-center text-white">Crie sua conta</h2>
            
            <p class="mt-3 text-gray-300">Informe os seus dados no formulário abaixo.</p>
        
        </div>

        <div class="mt-8">
                
            <%= render 'form', usuario: @usuario %>

            <h4 class="mx-2 my-4 font-medium text-white hover:underline">
                <%= link_to "Já tenho uma conta", login_path() %>
            </h4>

        </div>

    </div>

</div>

app/views/welcome/index.html.erb
<div class="flex flex-col w-full bg-white text-gray-600 shadow">
   
  <div class="flex justify-between h-16 content-center items-center">
    <p class="py-2 mx-4 text-4xl">Bemvindo</p>
  </div>

</div>

<div class="w-full my-4 mx-auto px-4 md:px-12">
  <ul>
    <div>
      <%= form_with(url: localizar_url, method: :get, data: {
                                                  controller: :maps,
                                                  action: "google-maps-callback@window->maps#initializeMap"
                                                }, class: "contents") do |form| %>      

        <div class="my-5 w-full">
          <%= form.text_field :nome, placeholder: "Para onde vamos?", data: { target: "maps.field", action: "keydown->maps#preventSubmit" }, class: "block shadow rounded-md border border-solid border-gray-300 outline-none px-3 py-2 mt-2 w-full" %>
        </div>  

        <div class="hidden">
          <%= form.text_field :latitude, value: -22.960567, data: { target: "maps.latitude" } %>
        </div>

        <div class="hidden">
          <%= form.text_field :longitude, value: -44.0419395, data: { target: "maps.longitude" } %>
        </div>        
        
        <%= content_tag :div, nil, data: { target: "maps.map" }, class: 'map-full' %>

      <% end %>
    </div>
  </ul>
</div>